export type ModelRegistrationConference = {
  id: string;
  tb_user_id: string;
  name_company: string;
  nick_trade: string;
  note: string;
  email: string;
  kind_phone: string;
  contact: string;
  number: string;
  address_kind: string;
  kind_address: string;
  address: string;
  nmbr: string ;
  complement: string;
  region: string;
  zip_code: string;
  country: string;
  opening_hours: string;
  link_map: string;
  state: string;
  city: string;
  created_at: string;
  updated_at: string;
};
